info:
  app:
    description: Eureka Service Registrar governs Environment Service Mesh
    name: eureka-server
    version: 1.0.0
  java:
    version: ${java.specification.version}
#
management:
  endpoints:
    web:
      exposure:
        exclude: flyway,liquibase
        include: '*'
  info:
    git:
      mode: full
#
eureka:
  datacenter: Local
  environment: ${groupname:DEV}
  numberRegistrySyncRetries: 0
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
  server:
    enable-self-preservation: false
    renewalPercentThreshold: 0.1
#
server:
  port: 8761
#
spring:
  application:
    name: eureka-server
# Spring Boot Admin Application
  boot:
    admin:
      context-path: /admin
